# -*- coding: utf-8 -*-
"""Think-week4-Lucille.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v-cegFDLBYL9GYeSHXy-UypDwZxbyKgU
"""

print("Hello World")

print("Hello!")
print("My name is Lucille.")

"""操作說明"""

